Repository openshift/router, pull requests merged in 2019-12, with the labels that each got.

#68 Bug 1780398: status: performIngressConditionUpdate: Retry on 403
  pkg/router/controller/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#69 Bug 1780794: unique_host: HandleRoute: No error if host claimed
  pkg/router/controller/unique_host.go
  pkg/router/template/plugin_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#71 images/router/haproxy: switch to haproxy 2.0
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
Labels: approved, lgtm, size/XS
