Repository openshift/router, pull requests merged in 2019-10, with the labels that each got.

#39 Bug 1723400: fix haproxy reload crash when processing ECDSA keys
  pkg/router/routeapihelpers/validation.go
  pkg/router/routeapihelpers/validation_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#43 test: use a cert with a 10-year expiration
  pkg/router/routeapihelpers/validation_test.go
Labels: approved, lgtm, size/M

#46 Delete obsolete F5 code
  pkg/cmd/infra/router/f5.go
  pkg/router/f5/f5.go
  pkg/router/f5/plugin.go
  pkg/router/f5/plugin_test.go
  pkg/router/f5/testing/deepcopy.go
  pkg/router/f5/testing/doc.go
  pkg/router/f5/testing/types.go
  pkg/router/f5/testing/zz_generated.deepcopy.go
  pkg/router/f5/types.go
Labels: approved, lgtm, size/XXL

#50 Delete tracking of peer endpoints
  pkg/cmd/infra/router/template.go
  pkg/router/template/plugin.go
  pkg/router/template/router.go
Labels: approved, lgtm, size/M

#53 Stop base64-encoding "router reloaded" log output
  pkg/router/template/router.go
Labels: approved, lgtm, size/XS

#51 Add ServiceUnitKey and ServiceAliasConfigKey types
  pkg/router/template/configmanager/haproxy/backend.go
  pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go
  pkg/router/template/configmanager/haproxy/client.go
  pkg/router/template/configmanager/haproxy/client_test.go
  pkg/router/template/configmanager/haproxy/manager.go
  pkg/router/template/configmanager/haproxy/map.go
  pkg/router/template/configmanager/haproxy/map_test.go
  pkg/router/template/fake.go
  pkg/router/template/plugin.go
  pkg/router/template/plugin_test.go
  pkg/router/template/router.go
  pkg/router/template/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
  pkg/router/template/types.go
Labels: approved, lgtm, size/L

#44 [release-4.2] Bug 1758373: fix haproxy reload crash when processing ECDSA keys
  pkg/router/routeapihelpers/validation.go
  pkg/router/routeapihelpers/validation_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#57 Bug 1691190: hostindex: Passthrough displaces path-based TLS routes
  pkg/router/controller/hostindex/activation.go
  pkg/router/controller/hostindex/hostindex_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#59 Bug 1691190: hostindex: Path-based TLS displaces passthrough
  pkg/router/controller/hostindex/activation.go
  pkg/router/controller/hostindex/hostindex_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
