Repository openshift/router, pull requests merged in 2019-02, with the labels that each got.

#13 image: Declare explicit dependency on sysvinit-tools
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
Labels: approved, lgtm, size/XS

#15 owners: update approvers and reviewers
  OWNERS
Labels: approved, lgtm, size/S

#14 Fix issue where wildcard routes get 503s intermittently.
  pkg/router/controller/host_admitter.go
  pkg/router/controller/host_admitter_test.go
Labels: approved, lgtm, size/L
