Repository openshift/router, pull requests merged in 2020-11, with the labels that each got.

#214 images/router: Update to haproxy22 package
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, lgtm

#209 Bug 1892338: metrics: Rework template_router_reload_failure metric
  pkg/router/template/router.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#210 Address gosec G601 issues
  pkg/router/controller/contention.go
  pkg/router/controller/status.go
  pkg/router/template/router.go
  pkg/router/template/template_helper.go
Labels: approved, lgtm

#196 Bug 1861383: Clip haproxy.router.openshift.io/timeout annotation values to prevent bricking on upgrade
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#219 addowner-candita
  OWNERS
Labels: approved, lgtm, ok-to-test
