Repository openshift/router, pull requests merged in 2020-10, with the labels that each got.

#190 Bug 1859134: Switch to periodic process reaper
  go.mod
  go.sum
  pkg/cmd/infra/router/template.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/listers/route/v1/route.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/proc/proc.go
  vendor/github.com/openshift/library-go/pkg/proc/proc_linux.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper.go
  vendor/github.com/openshift/library-go/pkg/serviceability/logrus.go
  vendor/github.com/openshift/library-go/pkg/serviceability/panic.go
  vendor/github.com/openshift/library-go/pkg/serviceability/profiler.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#194 Bug 1885414: haproxy-config.template: Only enable HTX for HTTP/2
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#197 Updating ose-haproxy-router-base builder & base images to be consistent with ART
  images/router/base/Dockerfile.rhel
Labels: approved, lgtm

#198 Updating openshift-enterprise-haproxy-router builder & base images to be consistent with ART
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, lgtm

#174 Allow configuring dontlognull/http-ignore-probes
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#204 Bug 1889863: Fix logging of namespace label selector
  pkg/cmd/infra/router/router.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
