Repository openshift/router, pull requests merged in 2020-07, with the labels that each got.

#105 Bug 1816540: [4.3] Backport "remove proto-version header field"
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#144 Bug 1854814: Removes ALPN from haproxy backends
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#145 Update owners
  OWNERS
Labels: approved, lgtm

#136 Bug 1843856: Sanitize TLS config that has key bundled with cert
  pkg/router/routeapihelpers/validation.go
  pkg/router/routeapihelpers/validation_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#138 Use generateCertKey consistently
  pkg/router/template/router.go
  pkg/router/template/template_helper.go
Labels: approved, lgtm

#139 Add HTTP header capture
  images/router/haproxy/conf/haproxy-config.template
  pkg/cmd/infra/router/template.go
  pkg/router/template/plugin.go
  pkg/router/template/router.go
  pkg/router/template/types.go
Labels: approved, lgtm

#153 Handle errors from commit and reload
  pkg/router/router_test.go
  pkg/router/template/router.go
Labels: approved, lgtm

#146 Allow configuring unique-id HTTP header
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#147 Add HTTP cookie capture
  images/router/haproxy/conf/haproxy-config.template
  pkg/cmd/infra/router/template.go
  pkg/router/template/plugin.go
  pkg/router/template/router.go
  pkg/router/template/types.go
Labels: approved, lgtm

#134 Allow configuring Forwarded/X-Forwarded-* headers
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#108 Use ServiceAliasConfigKeys for dynamic config
  pkg/router/template/configmanager/haproxy/blueprint_plugin_test.go
  pkg/router/template/configmanager/haproxy/manager.go
  pkg/router/template/types.go
Labels: approved, lgtm, ok-to-test

#155 Add Dockerfile.rhel8
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, lgtm

#154 Switch to EndpointSlices
  pkg/cmd/infra/router/router.go
  pkg/router/controller/endpointsubset/sort_address.go
  pkg/router/controller/endpointsubset/sort_port.go
  pkg/router/controller/factory/factory.go
  pkg/router/controller/router_controller.go
  pkg/router/template/plugin.go
Labels: approved, lgtm

#129 feat(route): Implements rewrite-target for ha-proxy
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/configmanager/haproxy/manager.go
Labels: approved, lgtm, ok-to-test
