Repository openshift/router, pull requests merged in 2020-08, with the labels that each got.

#161 Delete unnecessary OWNERS files
  images/router/OWNERS
  pkg/cmd/infra/router/OWNERS
  pkg/router/OWNERS
Labels: approved, lgtm

#162 [release-4.5] Sync OWNERS with master branch
  OWNERS
  images/router/OWNERS
  pkg/cmd/infra/router/OWNERS
  pkg/router/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#163 [release-4.4] Sync OWNERS with master branch
  OWNERS
  images/router/OWNERS
  pkg/cmd/infra/router/OWNERS
  pkg/router/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#164 [release-4.3] Sync OWNERS with master branch
  OWNERS
  images/router/OWNERS
  pkg/cmd/infra/router/OWNERS
  pkg/router/OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#165 Bug 1861455: Remove initial haproxy template commitAndReload
  pkg/router/template/router.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#169 Bug 1867971: extend unit tests for endpointslices
  go.mod
  go.sum
  pkg/cmd/infra/router/template.go
  pkg/router/controller/endpointsubset/sort_address.go
  pkg/router/controller/endpointsubset/sort_address_test.go
  pkg/router/controller/endpointsubset/sort_port.go
  pkg/router/controller/endpointsubset/sort_port_test.go
  pkg/router/controller/factory/factory.go
  pkg/router/controller/factory/factory_endpointslices_test.go
  pkg/router/controller/router_controller.go
  pkg/router/router_test.go
  vendor/github.com/fortytw2/leaktest/.travis.yml
  vendor/github.com/fortytw2/leaktest/LICENSE
  vendor/github.com/fortytw2/leaktest/README.md
  vendor/github.com/fortytw2/leaktest/leaktest.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#167 [release-4.5] Bug 1866454: Back port Remove initial haproxy template commitAndReload
  pkg/router/template/router.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
