Repository openshift/router, pull requests merged in 2020-09, with the labels that each got.

#178 Bug 1874278: Drop openssl to SECLEVEL=1 in Dockerfile
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#170 Bug 1858879: Change router's internal endpoint.ID to prevent HAProxy server line collisions
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
  pkg/router/template/plugin.go
  pkg/router/template/plugin_test.go
  pkg/router/template/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#140 Bug 1852728: haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant
  images/router/haproxy/conf/error-page-503.http
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#180 Bug 1878319: Allow trailing dots in host names
  pkg/router/template/template_helper_test.go
  pkg/router/template/util/haproxy/map_entry.go
  pkg/router/template/util/haproxy/map_entry_test.go
  pkg/router/template/util/util.go
  pkg/router/template/util/util_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#184 [release-4.5] Bug 1879120: Backport haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant
  images/router/haproxy/conf/error-page-503.http
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#179 Bug 1752814: Fix decreasing counter metrics when reloading HAProxy
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#185 [release-4.4] Bug 1879122: Backport haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant
  images/router/haproxy/conf/error-page-503.http
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#189 Bug 1867186: Add SameSite route annotation
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/configmanager/haproxy/manager.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
