Repository openshift/router, pull requests merged in 2020-12, with the labels that each got.

#226 Revert "images/router: Update to haproxy22 package"
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, lgtm

#229 Bug 1903206: Check Ready condition status in Endpointslices
  pkg/router/controller/router_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#224 Allow configuring HTTP header name case adjustment
  images/router/haproxy/conf/haproxy-config.template
  pkg/cmd/infra/router/template.go
  pkg/router/template/plugin.go
  pkg/router/template/router.go
  pkg/router/template/types.go
Labels: approved, lgtm

#231 Bug 1903206: Add unit tests to verify NotReadyAddresses in EndpointSlices
  pkg/router/controller/endpointsubset/converter.go
  pkg/router/controller/endpointsubset/converter_test.go
  pkg/router/controller/router_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#218 [release-4.5] Bug 1896914: Back port Clip haproxy.router.openshift.io/timeout annotation values to prevent bricking on upgrade
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#234 [release-4.5] Bug 1906132: back port: Change router's internal endpoint.ID to prevent HAProxy server line collisions
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
  pkg/router/template/plugin.go
  pkg/router/template/plugin_test.go
  pkg/router/template/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#202 [release-4.4] Bug 1886215: haproxy-config.template: Turn off HTX
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#233 Bug 1903821: Pass stop channel to RouterControllers
  pkg/cmd/infra/router/template.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
