Repository openshift/router, pull requests merged in 2020-04, with the labels that each got.

#52 Bug 1820400: Watch default certificate secret even if initial secret is invalid
  pkg/router/template/router.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#110 Set log level 2 by default
  cmd/openshift-router/main.go
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
Labels: approved, lgtm

#112 Set log-send-hostname in haproxy-config.template
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#114 build: Add verify target
  Makefile
  hack/verify-deps.sh
  hack/verify-gofmt.sh
  pkg/router/template/certmanager_test.go
Labels: approved, lgtm

#115 Add frobware to approvers
  OWNERS
Labels: approved, lgtm

#121 Bug 1825354: Removes ALPN from haproxy frontends
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#123 Bug 1826990: Removes ALPN from haproxy frontends
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/high, bugzilla/valid-bug, cherry-pick-approved, lgtm
