Repository openshift/router, pull requests merged in 2020-05, with the labels that each got.

#125 Bug 1832352: Enable ALPN http/2 on reencrypt and passthrough routes only
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/template_helper.go
  pkg/router/template/util/haproxy/map_entry.go
  pkg/router/template/util/haproxy/map_entry_test.go
  pkg/router/template/util/haproxy/types.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#127 Bug 1832539: Only a subset of router metrics should be preserved across restarts
  go.mod
  go.sum
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#128 Bug 1832629: Add metrics for 1xx, 3xx, and 4xx request counters, add latency, track reused connections
  pkg/router/metrics/haproxy/haproxy.go
  pkg/router/metrics/haproxy/haproxy_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#130 Bug 1813894: Stop using service ca from service account token
  pkg/cmd/infra/router/template.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#132 Bug 1835845: Report all backend metrics for when there are no endpoints
  pkg/router/metrics/haproxy/haproxy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#133 Bug 1837251: Add unsupported http/2 kill switch
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/router.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
