Repository openshift/router, pull requests merged in 2020-03, with the labels that each got.

#94 Bug 1809665: Start graceful shutdown on SIGTERM
  images/router/haproxy/reload-haproxy
  pkg/cmd/infra/router/template.go
  pkg/router/metrics/health.go
  pkg/router/shutdown/shutdown.go
  pkg/router/shutdown/signal_posix.go
  pkg/router/shutdown/signal_windows.go
  pkg/router/template/limiter/limiter.go
  pkg/router/template/plugin.go
  pkg/router/template/router.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#99 Bug 1810181: Wildcard is not needed to copy subdirectory in dockerfile
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
  images/router/nginx/Dockerfile
  images/router/nginx/Dockerfile.rhel
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#96 [release-4.2] Bug 1809398: Dynamically reload metrics certificate/key file changes
  pkg/cmd/infra/router/template.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
