Repository openshift/router, pull requests merged in 2021-07, with the labels that each got.

#317 Revert to haproxy22
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, lgtm

#277 reload-haproxy: Use curl --haproxy-protocol
  images/router/haproxy/reload-haproxy
Labels: approved, lgtm

#175 Reload client CA and CRL when updated
  pkg/router/template/router.go
Labels: approved, lgtm, lifecycle/rotten

#320 NE-412: Add ROUTER_INSPECT_DELAY
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#304 haproxy-config.template: Make maxconn optional
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#305 [release-4.8] Bug 1971730: error pages - don't use bootstrap/normalize
  images/router/haproxy/conf/error-page-404.http
  images/router/haproxy/conf/error-page-503.http
  images/router/nginx/conf/error-page-503.html
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#321 [release-4.8] Bug 1984565: config template: accept IPv6 IPs for whitelisting
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#322 Bug 1987238: Validate ROUTER_INSPECT_DELAY env value generating haproxy config
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, qe-approved
