Repository openshift/router, pull requests merged in 2021-03, with the labels that each got.

#266 Bug 1909906: Exit gracefully if metrics listener fails
  pkg/router/metrics/metrics.go
  pkg/router/shutdown/shutdown.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#268 Bug 1937972: router/template: Cache compiled regular expressions
  pkg/router/template/router.go
  pkg/router/template/template_helper.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#193 NE-417: Allow configuring HAProxy header buffer sizes
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#258 Bug 1925697: Route admission should not use the override
  pkg/router/controller/unique_host.go
  pkg/router/controller/unique_host_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#273 Bug 1942534: [4.7 backport] Route gets admitted with invalid host name if override annotation is used
  pkg/router/controller/unique_host.go
  pkg/router/controller/unique_host_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
