Repository openshift/router, pull requests merged in 2021-05, with the labels that each got.

#282 Bug 1947478: Switch from discovery v1beta1 to discovery v1
  pkg/router/controller/endpointsubset/converter.go
  pkg/router/controller/endpointsubset/converter_test.go
  pkg/router/controller/factory/factory.go
  pkg/router/controller/factory/factory_endpointslices_test.go
  pkg/router/controller/router_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#285 Bug 1961550: Add a condition to check if the Endpoints ID is duplicated
  pkg/router/template/plugin.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#290 Bug 1957584: Revert 'Bug 1896977: Enhance host name validation in router'
  pkg/router/controller/host_admitter.go
  pkg/router/controller/host_admitter_test.go
  pkg/router/controller/unique_host.go
  pkg/router/controller/unique_host_test.go
  vendor/github.com/openshift/library-go/pkg/route/routeapihelpers/routeapihelpers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, qe-approved
