Repository openshift/router, pull requests merged in 2021-02, with the labels that each got.

#237 Add rfredette to OWNERS
  OWNERS
Labels: approved, lgtm

#83 Bug 1801407: Omit brackets around IPv4 addresses in v4v6 mode
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#259 Switch to haproxy22
  images/router/haproxy/Dockerfile
  images/router/haproxy/Dockerfile.rhel
  images/router/haproxy/Dockerfile.rhel8
Labels: approved, lgtm

#261 template: Drop http-use-htx option
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm

#240 Bug 1903821: contention: Contend over route ingress admission condition
  pkg/router/controller/contention.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
