Repository openshift/router, pull requests merged in 2021-06, with the labels that each got.

#291 Bug 1955822: cmd: Add option to source stats auth from file
  pkg/cmd/infra/router/template.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#295 Bug 1964486: template helper - generateHAProxyWhiteListFile, use right arg type
  pkg/router/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#300 Bug 1967228: error pages - don't use bootstrap/normalize
  images/router/haproxy/conf/error-page-404.http
  images/router/haproxy/conf/error-page-503.http
  images/router/nginx/conf/error-page-503.html
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#299 Hack: Add initial hacking instructions
  HACKING.md
  hack/Dockerfile.debug
  hack/Makefile.debug
Labels: approved, lgtm

#287 Add alebedev87 to OWNERS
  OWNERS
Labels: approved, lgtm

#298 Bug 1953113: template config - HSTS header's pattern accepts case insensitive and white spaces
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/router_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#307 Bug 1964482: config template: accept IPv6 IPs for whitelisting
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/router_test.go
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
