Repository openshift/router, pull requests merged in 2022-04, with the labels that each got.

#379 Bug 2025624: Fix certificate reloader
  pkg/cmd/infra/router/template.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#381 Bug 2074304: generateRouteHostRegexp: Escape blanks
  pkg/router/template/util/haproxy/map_entry_test.go
  pkg/router/template/util/util.go
Labels: approved, lgtm, bugzilla/valid-bug

#383 Bug 2076297: Fix gap in router's handling of graceful shutdowns.
  pkg/router/controller/factory/factory.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#377 NE-822 Don't scale route weight on single service routes
  pkg/router/template/router.go
  pkg/router/template/router_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#357 NE-882: Support subdomain field when host is unset
  pkg/cmd/infra/router/router.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
