Repository openshift/router, pull requests merged in 2024-05, with the labels that each got.

#587 OCPBUGS-26498: Optimize Upgrade Validation plugin by skipping unnecessary changes
  pkg/router/controller/status.go
  pkg/router/controller/status_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#589 OCPBUGS-29373: generateHAProxyCertConfigMap: No H2 with dup certs
  pkg/router/router_test.go
  pkg/router/template/router.go
  pkg/router/template/template_helper.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#568 OCPBUGS-30773: OCPBUGS 6958 backport to 4.14
  pkg/router/template/template_helper.go
  pkg/router/template/template_helper_test.go
  pkg/router/template/util/haproxytime/duration_parser.go
  pkg/router/template/util/haproxytime/duration_parser_test.go
  pkg/router/template/util/util.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#581 [release-4.12] OCPBUGS-33517: Count active services before setting weight to 1
  pkg/router/template/router.go
  pkg/router/template/router_test.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#565 CFE-1020: feature:route external certificate reference
  go.mod
  go.sum
  pkg/cmd/infra/router/router.go
  pkg/cmd/infra/router/template.go
  pkg/router/controller/route_secret_manager.go
  pkg/router/controller/route_secret_manager_test.go
  pkg/router/routeapihelpers/validation.go
  pkg/router/router_test.go
  pkg/router/template/fake.go
  pkg/router/template/plugin.go
  pkg/router/template/router.go
  pkg/router/template/router_test.go
  vendor/github.com/openshift/api/route/.codegen.yaml
  vendor/github.com/openshift/api/route/v1/custom.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/stable.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/techpreview.route.testsuite.yaml
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/client-go/project/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/fake/fake_projectrequest.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/localobjectreference.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/routehttpheader.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/routehttpheaderactions.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/routehttpheaderactionunion.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/routehttpheaders.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/routesethttpheader.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/routespec.go
  vendor/github.com/openshift/client-go/route/applyconfigurations/route/v1/tlsconfig.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route.go
  vendor/github.com/openshift/library-go/pkg/authorization/authorizationutil/subject.go
  vendor/github.com/openshift/library-go/pkg/authorization/authorizationutil/util.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/proc/proc_linux.go
  vendor/github.com/openshift/library-go/pkg/route/secretmanager/fake/fake_manager.go
  vendor/github.com/openshift/library-go/pkg/route/secretmanager/manager.go
  vendor/github.com/openshift/library-go/pkg/secret/OWNERS
  vendor/github.com/openshift/library-go/pkg/secret/monitor.go
  vendor/github.com/openshift/library-go/pkg/secret/secret_monitor.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#583 [release-4.14] OCPBUGS-32634: Properly handle rewrite-target annotation
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/template_helper.go
  pkg/router/template/util/rewritetarget/rewritetarget.go
  pkg/router/template/util/rewritetarget/rewritetarget_test.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
