Repository openshift/router, pull requests merged in 2024-11, with the labels that each got.

#635 NE-1790: Enable setting zero pool size for blueprint routes via environment variable
  pkg/cmd/infra/router/template.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#636 NE-1815: Activate dynamic cookies for dynamic server slots (DCM)
  images/router/haproxy/conf/haproxy-config.template
Labels: approved, lgtm, jira/valid-reference

#627 OCPBUGS-42972: Support appProtocol: kubernetes.io/h2c
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/router_test.go
  pkg/router/template/configmanager/haproxy/backend.go
  pkg/router/template/configmanager/haproxy/manager.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#637 NE-1815: Add verifyhost to dynamic server slots for re-encrypt routes (DCM)
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/router_test.go
  pkg/router/template/plugin_test.go
  pkg/router/template/router.go
  pkg/router/template/types.go
Labels: approved, lgtm, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only
