Repository openshift/router, pull requests merged in 2024-03, with the labels that each got.

#566 OCPBUGS-30314: Refactor logging in DoHTTPProbe to avoid serialisation errors
  pkg/router/metrics/probehttp/probehttp.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#567 NO-JIRA: hack/Dockerfile.debug: use ubi9 for base image
  hack/Dockerfile.debug
Labels: approved, lgtm, jira/valid-reference

#534 OCPBUGS-22739: Properly handle rewrite-target annotation
  images/router/haproxy/conf/haproxy-config.template
  pkg/router/template/template_helper.go
  pkg/router/template/util/rewritetarget/rewritetarget.go
  pkg/router/template/util/rewritetarget/rewritetarget_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
